B-16522: Updated JSON for Availability
siostechcorp/DataKeeper_Signal pull request #2
Opened 2018-03-14 15:24 UTC by travisgoldie

2018-03-20 14:20 UTC, thorste commented
The diff looks fine (I only see word replacement).  Let's see if we can update the binary flag on those files though.

2018-03-20 14:23 UTC, srazin requested changes
can we split this into two? 1 to get rid of the binary so we actually could diff json, and another would actual include the changes

2018-03-20 14:59 UTC, thorste commented
Looks good

2018-04-02 15:39 UTC, srazin approved these changes

2018-04-02 15:43 UTC, merged